const { SlashCommandBuilder, PermissionFlagsBits, ChatInputCommandInteraction, EmbedBuilder } = require('discord.js');



module.exports = {

          data: new SlashCommandBuilder()

                   .setName('mute')

                            .setDescription('Mute a server user')

                                     .addUserOption(option =>

                                                  option.setName('user')

                                                                   .setDescription('Choose the user you want to mute')

                                                                                    .setRequired(true)

                                                                                             )

                                                                                                      .addStringOption(option =>

                                                                                                                   option.setName('time')

                                                                                                                                    .setDescription('Mute duration')

                                                                                                                                                     .addChoices(

                                                                                                                                                                          { name: "60 seconds", value: "60" },

                                                                                                                                                                                               { name: "2 minutes", value: "120" },

                                                                                                                                                                                                                    { name: "5 minutes", value: "300" },

                                                                                                                                                                                                                                         { name: "10 minutes", value: "600" },

                                                                                                                                                                                                                                                              { name: "15 minutes", value: "900" },

                                                                                                                                                                                                                                                                                   { name: "20 minutes", value: "1200" },

                                                                                                                                                                                                                                                                                                        { name: "30 minutes", value: "1800" },

                                                                                                                                                                                                                                                                                                                             { name: "45 minutes", value: "2700" },

                                                                                                                                                                                                                                                                                                                                                  { name: "3 hours", value: "10000" },

                                                                                                                                                                                                                                                                                                                                                                       { name: "10 hours", value: "36000" },

                                                                                                                                                                                                                                                                                                                                                                                            { name: "1 day", value: "86400" },

                                                                                                                                                                                                                                                                                                                                                                                                                 { name: "5 days", value: "432000" },

                                                                                                                                                                                                                                                                                                                                                                                                                                      { name: "1 week", value: "604800" },

                                                                                                                                                                                                                                                                                                                                                                                                                                                       )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setRequired(true)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .addStringOption(option =>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       option.setName('reason')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .setDescription('Mute reason')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .setRequired(false)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ),

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       /**

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             *

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   * @param { ChatInputCommandInteraction } interaction

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              async execute(interaction, client) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       const user = interaction.options.getUser("user");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const timeMember = await interaction.guild.members.fetch(user.id).catch(console.error);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         const time = interaction.options.getString("time");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const { guild } = interaction;



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const embed = new EmbedBuilder()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         .setColor("DarkButNotBlack")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .setDescription("❌ | You don't have enough permissions")

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return await interaction.reply({ embeds: [embed], ephemeral: true }).then(inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!timeMember) return await interaction.reply({ content: 'The mentioned user is no longer on the server', ephemeral: true }).then(inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!timeMember.kickable) return interaction.reply({ content: "You cannot mute someone with a higher role than you", ephemeral: true }).then(inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (!time) return interaction.reply({ content: "You must set a valid duration for the timeout", ephemeral: true }).then(inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (interaction.member.id === timeMember.id) return interaction.reply({ content: "You cannot mute yourself", ephemeral: true }).then(inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (timeMember.permissions.has(PermissionFlagsBits.Administrator)) return interaction.reply({ content: "You cannot mute staff members or people with administrator permissions!", ephemeral: true }).then( inter => {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                setTimeout(() => inter.interaction.deleteReply(), 8 * 1000);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         })



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  let reason = interaction.options.getString("reason");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           if (!reason) reason = "No reason was specified";



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await timeMember.timeout(time * 1000, reason).catch(console.error);



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             const embedKick = new EmbedBuilder()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .setTitle('Muted User')

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       .setDescription(`User ${user} was muted from the server`)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setFields(

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     { name: 'Reason:', value: `\`\`\`yaml\n${reason}\`\`\`` },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { name: 'User:', value: `${user}`, inline: true },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       { name: 'Staff:', value: `${interaction.user}`, inline: true },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { name: 'Time', value: `${time / 60} minute(s)`, inline: true }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     )

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  .setThumbnail(`${user.displayAvatarURL()}`)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               .setColor("DarkButNotBlack");



                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        interaction.reply({ embeds: [embedKick] });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             },

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             };